# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-19 18:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='complete',
            new_name='completed',
        ),
    ]
